name: MobSF Scan

on: [push,pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - run: |
          sudo mkdir -p /home/runner/work/_temp/_github_home
          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

          sudo mkdir -p /home/runner/work/$myRepoName/$myRepoName
          sudo chown -R 9901:9901 /home/runner/work/$myRepoName/$myRepoName

      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@v1.7.2
        env:
          INPUT_FILE_NAME: Find_my_Data.ipa
          SCAN_TYPE: ipa
          OUTPUT_FILE_NAME: mobsf-report

      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.pdf
          path: mobsf-report.pdf

      - name: Upload MobSF Analysis JSON Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.json
          path: mobsf-report.json
